# Generated by Django 3.2 on 2021-05-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='addres',
            new_name='address',
        ),
    ]
